### ISSUE TITLE
Avoid conditional logic in modules

### ISSUE THREAD

**Issue by koriym** [kuma-guy/BEAR.JwtAuthenticationModule#1]
https://github.com/kuma-guy/BEAR.JwtAuthenticationModule/blob/master/src/JwtAuthenticationModule.php#L115-L119

We should have two separate module in this case ?
see more at https://github.com/google/guice/wiki/AvoidConditionalLogicInModules .

**Comment by kuma-guy** [comment]
Thanks! This issue is fixed in #2 :)

**Comment by koriym** [comment]
nice
